# Indexing
ARTICLES_PER_INTERMED_FILE = 10000
INTERMED_DIR = 'intermed'
INTERMED_FILE_WRITE_BUFFER = -1

TOKENS_PER_FILE = 10000
TITLES_FILE = 'titles'

MAX_INDEXED_WORD_LENGTH = 43
MIN_INDEXED_WORD_LENGTH = 1
MAX_ESTIMATED_INFOBOX_LENGTH = 1000