# Indexing
ARTICLES_PER_INTERMED_FILE = 10000
INTERMED_DIR = 'intermed'
INTERMED_FILE_WRITE_BUFFER = -1

TOKENS_PER_FINAL_FILE = 10000
INTERMED_FILE_READ_BUFFER = -1
TITLES_DIR = 'titles'
TITLES_PER_FILE = 200000
FIRST_WORD_FILE = 'heads.txt'

MAX_INDEXED_WORD_LENGTH = 43
MIN_INDEXED_WORD_LENGTH = 2
MAX_INDEXED_NUM_LENGTH = 4
MAX_ESTIMATED_INFOBOX_LENGTH = 1000